### ISSUE TITLE
Search form returns different results depending on where you search from (bug)

### ISSUE THREAD

**Issue by mozboz** [hoegrammer/opencase#55]
replicate: 

on demo site, after login click search with nothing in the search box.
right now for me this returns 3 records: Emma Goldman, Jane Doe, John Smith
if I immediately click search again, again with nothing in search box, I then get 11 (all?) records.

**Comment by hoegrammer** [comment]
Need to test this when changing permissions and adding people. I think it's to do with cacheing.

**Comment by hoegrammer** [comment]
definitely a caching thing.

When I clicked it without any terms it only showed one person and then I made Matthew an account and his showed a lot more. 

Re-indexing made them all come up for me too

**Comment by hoegrammer** [comment]
seems ok to me now so long as you actually put in some terms.
