### ISSUE TITLE
demo.opencase.org is down

### ISSUE THREAD

**Issue by lwm** [hoegrammer/opencase#77]
Hey there :)

http://demo.opencase.org/

![screenshot from 2018-05-15 11-27-24](https://user-images.githubusercontent.com/1991377/40048616-f60b3950-5832-11e8-9153-92fbcdfbd516.png)

**Comment by hoegrammer** [comment]
Nah I just gave you the wrong address! Add .UK on the end. Sorry!

**Comment by lwm** [comment]
:)
